### ISSUE TITLE
deduplicate entries

### ISSUE THREAD

**Issue by Jorropo** [mvdan/corpus#11]
> ```tsv
> k8s.io/kops	d8ce157d81e704dfdac0412fcb2b0de74553952d	https://github.com/kubernetes/kops	18757
> k8s.io/kops	d8ce157d81e704dfdac0412fcb2b0de74553952d	https://github.com/kubernetes/kops	18757
> ```

On commit https://github.com/mvdan/corpus/commit/1ae32d9009c32dcf3f6759e4c0f8fdc370f4d518 there is a duplicate entry.

**Comment by mvdan** [comment]
We need to do the search [in chunks via multiple queries](https://github.com/mvdan/corpus/blob/1ae32d9009c32dcf3f6759e4c0f8fdc370f4d518/main.go#L175-L177), and that means that sometimes we will end up with overlapping modules. We should probably deduplicate those. Want to send a PR?
