### ISSUE TITLE
CI: github seems to have lowered the GraphQL API rate limits

### ISSUE THREAD

**Issue by mvdan** [mvdan/corpus#9]
Our weekly sync job has been failing for some weeks. See https://github.com/mvdan/corpus/pull/7#issuecomment-842102840.

Perhaps one fix is to add sleeps between each API request?

The requests already use a personal access token on my account, so that should be as much API access as one can get without having an enterprise account/setup.

**Comment by mvdan** [comment]
> yeah, I'm gonna take a crack at it.

@khos2ow I've invited you to the repo. I think write access should be enough for you to test/debug stuff. If you also need admin access to set up secrets, just let me know.

**Comment by mvdan** [comment]
Ah, scratch that, I can only give write access to a personal repo. Giving out admin access requires using an org.

**Comment by khos2ow** [comment]
Sounds great. I don't think I'd need admin access, as my idea to make it work with any normal token, so then I should be able to reuse default `GITHUB_TOKEN` available on the actions.

**Comment by khos2ow** [comment]
I'm gonna assign this to myself for visibility.

**Comment by mvdan** [comment]
My personal access token (with no extra permissions) certainly did not seem to give us a higher rate limit than the default GITHUB_TOKEN.
